name: 'nbdev-ci'
description: 'Test with nbdev'
inputs:
  pre:
    description: 'Install prerelease nbdev/execnb from master?'
    required: false
    default: ''
  version:
    description: 'Version of python to set up'
    required: false
    default: '3.9'

runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.version }}
        cache: "pip"
        cache-dependency-path: settings.ini
    - name: Test with nbdev
      env:
        USE_PRE: ${{ inputs.pre }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ $USE_PRE ]; then
          pip install -U git+https://github.com/fastai/fastcore.git
          pip install -U git+https://github.com/fastai/ghapi.git
          pip install -U git+https://github.com/fastai/execnb.git
          pip install -U git+https://github.com/fastai/nbdev.git
        else
          pip install -U nbdev
        fi
        pip install -qe ".[dev]"
        echo "Check we are starting with clean git checkout"
        if [[ `git status --porcelain -uno` ]]; then
          git diff
          echo "git status is not clean"
          false
        fi
        echo "Trying to strip out notebooks"
        nbdev_clean
        echo "Check that strip out was unnecessary"
        git status -s # display the status to see which nbs need cleaning up
        if [[ `git status --porcelain -uno` ]]; then
          git status -uno
          echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
          false
        fi
        nbdev_export
        if [[ `git status --porcelain -uno` ]]; then
          echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
          git status -uno
          git diff
          exit 1;
        fi
        nbdev_test

